export const rewardItems = [
  {
    rewardName: 'คูปองส่วนลด Too Fast To Sleep',
    rewardId: 'toofasttosleep20',
    description: 'มูลค่า 20 บาท',
    point: 20,
    img: 'reward06.png',
    available: true,
  },
  {
    rewardName: 'คูปองส่วนลด KOI The',
    rewardId: 'koi50',
    description: 'มูลค่า 50 บาท',
    point: 50,
    img: 'reward04.png',
    available: true,
  },
  {
    rewardName: 'คูปองส่วนลด Momo - Paradise',
    rewardId: 'momo100',
    description: 'มูลค่า 100 บาท',
    point: 100,
    img: 'reward01.png',
    available: false,
  },
  {
    rewardName: 'คูปองส่วนลด Shopee',
    rewardId: 'shopee',
    description: 'มูลค่า 100 บาท',
    point: 100,
    img: 'reward02.png',
    available: false,
  },
  {
    rewardName: 'คูปองส่วนลด MUJI',
    rewardId: 'muji',
    description: 'มูลค่า 200 บาท',
    point: 200,
    img: 'reward03.png',
    available: false,
  },
  {
    rewardName: 'คูปองส่วนลดรองเท้า New Balance',
    rewardId: 'nb500',
    description: 'มูลค่า 500 บาท',
    point: 200,
    img: 'reward05.png',
    available: false,
  },
  {
    rewardName: 'คูปองแลกสกิน ROV',
    rewardId: 'rov',
    description: 'สกินระดับ Heroic',
    point: 100,
    img: 'reward07.png',
    available: false,
  },
  {
    rewardName: 'คูปองส่วนลด SOS',
    rewardId: 'sos',
    description: 'มูลค่า 150 บาท',
    point: 150,
    img: 'reward08.png',
    available: false,
  },
  {
    rewardName: 'คูปองส่วนลด Bonchon',
    rewardId: 'bonchon',
    description: 'มูลค่า 150 บาท',
    point: 150,
    img: 'reward09.png',
    available: false,
  },
];
